# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-22 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Titre')),
                ('date', models.DateField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField(verbose_name='Contenu')),
                ('resume', models.TextField(verbose_name='Résumé')),
            ],
            options={
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=50, verbose_name='Nom du visiteur')),
                ('commenter_email', models.CharField(max_length=50, verbose_name='Email du visiteur')),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField(verbose_name='Contenu')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article', verbose_name='Article')),
            ],
            options={
                'verbose_name_plural': 'Commentaires',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articles.Category', verbose_name='Catégorie'),
        ),
    ]
