# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-04 20:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180404_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 4, 20, 42, 37, 270083)),
        ),
    ]
