# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-05 15:53
from __future__ import unicode_literals

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20180404_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.FileField(default=None, upload_to='', validators=[articles.models.validate_file_extension], verbose_name='Image'),
            preserve_default=False,
        ),
    ]
